In [2]:
from keras.datasets import boston_housing
(train_data,train_labels),(test_data,test_labels)=boston_housing.load_data()
print(train_data.shape)

57026/57026 ━━━━━━━━━━━━━━━━━━━━ 0s 2us/step
(404, 13)


In [4]:
test_data.shape

(102, 13)

In [11]:
train_data[0]

array([-0.67803164, -0.96723094, -2.06807658, -0.5136655 , -4.92294051,
       -9.01690729, -1.65990045, -1.7278891 , -1.71292507, -3.03786224,
       -7.2586309 , -3.32642867, -0.93321053])

In [12]:
mean=train_data.mean(axis=0)
mean

array([-0.40578531, -0.48361547, -1.63231497, -0.25683275, -4.75771391,
       -8.84046469, -2.47296233, -1.8445874 , -1.08667602, -2.44269221,
       -8.40713134, -3.7745058 , -1.75843073])

In [13]:
train_data-=mean
train_data

array([[-0.27224633, -0.48361547, -0.43576161, ...,  1.14850044,
         0.44807713,  0.8252202 ],
       [-0.40342651,  2.99178419, -1.33391162, ..., -1.71818909,
         0.43190599, -1.32920239],
       [ 0.1249402 , -0.48361547,  1.0283258 , ...,  0.78447637,
         0.22061726, -1.30850006],
       ...,
       [-0.40202987,  0.99079651, -0.7415148 , ..., -0.71712291,
         0.07943894, -0.67776904],
       [-0.17292018, -0.48361547,  1.24588095, ..., -1.71818909,
        -0.98764362,  0.42083466],
       [-0.40422614,  2.04394792, -1.20161456, ..., -1.30866202,
         0.23317118, -1.15392266]])

In [14]:
std=train_data.std(axis=0)
train_data/=std
train_data

array([[-0.27224633, -0.48361547, -0.43576161, ...,  1.14850044,
         0.44807713,  0.8252202 ],
       [-0.40342651,  2.99178419, -1.33391162, ..., -1.71818909,
         0.43190599, -1.32920239],
       [ 0.1249402 , -0.48361547,  1.0283258 , ...,  0.78447637,
         0.22061726, -1.30850006],
       ...,
       [-0.40202987,  0.99079651, -0.7415148 , ..., -0.71712291,
         0.07943894, -0.67776904],
       [-0.17292018, -0.48361547,  1.24588095, ..., -1.71818909,
        -0.98764362,  0.42083466],
       [-0.40422614,  2.04394792, -1.20161456, ..., -1.30866202,
         0.23317118, -1.15392266]])

In [15]:
train_data.shape

(404, 13)

In [24]:
from keras import layers,models
def build_model():
    model=models.Sequential()
    model.add(layers.Dense(64,activation='relu',input_shape=(13,)))
    model.add(layers.Dense(64,activation='relu'))
    model.add(layers.Dense(1))
    model.compile(optimizer='rmsprop',loss='mse',metrics=['mae'])
    return model

In [25]:
import numpy as np
k=4
num_val_samples=len(train_data)//4
num_val_samples

101

In [26]:
num_epochs=20
all_scores=[]
for i in range(k):
    val_data=train_data[i*num_val_samples:(i+1)*num_val_samples]
    val_target=train_labels[i*num_val_samples:(i+1)*num_val_samples]
    partial_train_data=np.concatenate([train_data[:i*num_val_samples],train_data[(i+1)*num_val_samples:]],axis=0)
    partial_train_label=np.concatenate([train_labels[:i*num_val_samples],train_labels[(i+1)*num_val_samples:]],axis=0)
    model=build_model()
    model.fit(partial_train_data,partial_train_label,epochs=num_epochs,batch_size=1)
    val_mse,val_mae=model.evaluate(val_data,val_target)
    all_scores.append(val_mse)

C:\Users\archa\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/20
303/303 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 371.5974 - mae: 16.3571
Epoch 2/20
303/303 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 37.8879 - mae: 4.4126
Epoch 3/20
303/303 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 20.5884 - mae: 3.0512
Epoch 4/20
303/303 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 24.2812 - mae: 3.2388
Epoch 5/20
303/303 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 15.6745 - mae: 2.6412
Epoch 6/20
303/303 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12.4416 - mae: 2.3116
Epoch 7/20
303/303 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.6495 - mae: 2.2035
Epoch 8/20
303/303 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 23.4567 - mae: 2.7915
Epoch 9/20
303/303 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.7439 - mae: 2.1697
Epoch 10/20
303/303 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12.8911 - mae: 2.3323
Epoch 11/20
303/303 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10.0846 - mae: 2.2142
Epoch 12/20
303/303 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12.0569 - mae: 2.2366
Epoch 13/20
3

303/303 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.7664 - mae: 2.1735
Epoch 9/20
303/303 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12.7574 - mae: 2.2821
Epoch 10/20
303/303 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.2526 - mae: 2.0397
Epoch 11/20
303/303 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12.2154 - mae: 2.1126
Epoch 12/20
303/303 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.6505 - mae: 1.9829
Epoch 13/20
303/303 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.0740 - mae: 1.8388
Epoch 14/20
303/303 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12.5173 - mae: 2.2546
Epoch 15/20
303/303 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.1025 - mae: 1.8269
Epoch 16/20
303/303 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.4013 - mae: 1.8650
Epoch 17/20
303/303 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.5533 - mae: 1.8356
Epoch 18/20
303/303 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10.3365 - mae: 2.0656
Epoch 19/20
303/303 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.8761 - mae: 1.8646
Epoch 20/20
303/303 ━━━━━

In [27]:
print(all_scores)

[10.419962882995605, 9.852874755859375, 13.960946083068848, 18.034509658813477]


In [28]:
np.mean(all_scores)

13.067073345184326